name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x
      
      - name: Cache Dependecies
        uses: c-hive/gha-yarn-cache@v2
      
      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run Linter
        run: yarn lint